### PR TITLE
Enable RSS feed plugin

### PR DESCRIPTION
**Pull request by mikecsh**
Untested but based on: https://help.github.com/articles/atom-rss-feeds-for-github-pages/

### CODE REVIEW

**Comment by VaporNationTravis** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please add a new entry to the <code>README.md</code> file before merging to master.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please add a new entry to the <code>index.md</code> file before merging to master.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by twof** [comment]
Any idea how I'd go about testing this?

**Comment by mikecsh** [comment]
I think if you run Jekyll locally, it should create a feed.xml file in the _site folder - I don't have Jekyll set up on this machine so can't test it out at the moment I'm afraid. Theres some detail on the linked page.

**Comment by twof** [comment]
ahh yup. Well. I guess I'll merge it in and try to subscribe to my page

**Comment by twof** [comment]
Thanks!

**Comment by twof** [comment]
Okay so it looks like `feed.xml` got generated
https://twof.github.io/VaporNation/feed.xml
No content in it though. I don't know if it detects previous posts

**Comment by mikecsh** [comment]
Hm okay, I'll look into it more and get back to you! Would be nice to have.

**Pull request merged**
